import Link from "next/link";
import { PageShell } from "../../components/SiteHeader";
import { chapters, getChapterPath } from "../../content/chapters";

export default function TeachersPage() {
  const chapter = chapters[0];
  const chapterPath = getChapterPath(chapter);
  return <PageShell><main className="page-main narrow" id="main"><div className="page-intro"><span className="eyebrow">For lærere</span><h1>Fra læringsmål til lange linjer</h1><p>Portalen er laget som den autoritative versjonen av fagtekster, nettoppgaver, kilder, oppsummeringer, lange linjer, begreper og tidslinjepunkter.</p></div><div className="columns-2"><article className="content-box"><h2>Den pedagogiske modellen</h2><p><strong>Fakta → forståelse → lange linjer.</strong> Elevene bygger først sikre punkter, kobler dem til årsaker og virkninger, og vurderer deretter hvordan en utvikling kan ses i et større historisk mønster.</p></article><article className="content-box ochre"><h2>Bruk sammen med OneNote</h2><p>Bruk OneNote til ukeplaner, lærerens gjennomgang, notater, arbeidsbeskjeder, elevsvar og lenker til riktig kapittel eller oppgavesett.</p></article></div><section className="section-block"><div className="section-heading"><span className="eyebrow">Kompetansemål</span><h2>Kapittel {chapter.number} treffer</h2></div><ul className="fact-list">{chapter.competenceGoals.map((goal) => <li key={goal}>{goal}</li>)}</ul></section><section className="section-block"><div className="section-heading"><span className="eyebrow">Undervisningspakke</span><h2>Hva er ferdig?</h2></div><ul className="resource-list">{chapter.teacherResources?.map((resource) => <li key={resource.label}><strong>{resource.label}</strong><span>{resource.description}</span></li>)}<li><strong>Nettoppgaver</strong><span>{chapter.tasks.length} oppgaver med hint, forklaringer og modellresponser. <Link href={`${chapterPath}#oppgaver`}>Åpne oppgavesettet →</Link></span></li><li><strong>Kort oppsummerings-PDF</strong><span>Ikke levert i kildematerialet ennå. Ingen fil lenkes før den er kvalitetssikret og lagt i prosjektet.</span></li></ul></section><section className="section-block"><div className="content-box"><h2>Under utvikling</h2><p>De øvrige kapitlene, flere tilknyttede PDF-er og eventuelle offentlig valgte lærerressurser kommer trinnvis. Hemmelige prøver og fasiter legges ikke på en offentlig nettside uten et bevisst publiseringsvalg.</p></div></section></main></PageShell>;
}
